//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recklama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recklama
    {
        public int id { get; set; }
        public Nullable<int> idOrganization { get; set; }
        public Nullable<int> idNewspaper { get; set; }
        public Nullable<long> Number { get; set; }
        public Nullable<long> Volume { get; set; }
    
        public virtual Newspaper Newspaper { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
